Add liquipedia-matches extension (#18455)
* Add liquipedia-matches extension

- Added new icon
- Added new icon
- Changed README
- Initial commit for Liquipedia Matches Raycast extension

* Made suggested changes

* fixed double parse

* fixed TS2339: Property \'parse\' does not exist on type \'unknown\'

* Update liquipedia-matches extension

- Double parse fixed
- Necessary changes made
- Changed README
- Initial commit for Liquipedia Matches Raycast extension

* Update liquipedia-matches extension

- Refactored the whole code to more robust logic
- Fixed Error: src/lib/getUpcomingMatches.ts(46,11): error TS2339: Property \'parse\' does not exist on type \'unknown\'.     Error: TypeScript check failed (Command failed with exit code 2:     ./node_modules/.bin/tsc -p tsconfig.json --noEmit) Error:     ./node_modules/.bin/tsc -p tsconfig.json --noEmit) Error: Process completed with exit code 1.

* Fixed times

* Added cached promise - metadata and small fixes

* Fix CI

* Update CHANGELOG.md and optimise images

---------

Co-authored-by: Per Nielsen Tikær <per@raycast.com>
Co-authored-by: raycastbot <bot@raycast.com>