Update MLB Scores Extension (#14635)
* adding in latest play to mlb scores

* Updating strikes, balls, and outs display. adding inning accessory to index

* MLB Scores: adding box score, adding view on mlb, adding latest play to index, updating screenshots

* MLB scores: updating metadata

* MLB Scores enforcing all caps changelog

* Fixed sorting, added data refreshing (15 seconds when game is live, 10 mins when no games). Fixed ERA and AVG

* Fixed type issues, bugs with first time loading

* MLB Scores: Adding Store, code cleanup, adding README

* MLB Scores: Lint fixes

* Fixed bug where reloadData wasn't being set to false, leading to the data not being updated

* MLB Scores: Updating box score display in games

* MLB Scores: Moving game details to metadata, adding in pitch sequence metadata

* MLB scores: combining R and RBI into same column to save space

* MLB Scores: updating screenshots for the store

* MLB Scores: merging PR from jso8910 to fix auto reload, ray lint fix

* MLB Scores: fixing tserror in run ray cli

src/components/game.tsx(80,19): error TS2339: Property 'reloadData' does not exist on type 'GameDataState'.
src/components/game.tsx(80,31): error TS2339: Property 'setReloadData' does not exist on type 'GameDataState'.
TypeScript check failed (exit status 2)

* MLB Scores: Unifying metadata screenshots

* Update CHANGELOG.md and optimise images

---------

Co-authored-by: jso8910 <mail4jasonr@gmail.com>
Co-authored-by: raycastbot <bot@raycast.com>