Adding support for more than one Elgato Key Light (#4821)
* Adding support for more than one Key Light

I updated the core parts of the extension to remove the assumption that there is a single Elgato Key Light. To do this I needed to add an array of Key Lights and then modify each function to loop through the array. This also required that the user tell us how many lights they have.

* Fixing failure in original extension

The original extension did not address some issues:

ℹ️  info  -  entry points [src/toggle.ts src/increaseBrightness.ts src/decreaseBrightness.ts src/increaseTemperature.ts src/decreaseTemperature.ts]
253
src/decreaseBrightness.ts(7,31): error TS18048: 'brightness' is possibly 'undefined'.
254
src/increaseBrightness.ts(9,31): error TS18048: 'brightness' is possibly 'undefined'.
255
TypeScript check failed (exit status 2)
256
Error: TypeScript check failed (exit status 2)
257
Error: Process completed with exit code 1.